### ISSUE TITLE
Выяснить вопросы по ТЗ Орбиты

### ISSUE THREAD

**Issue by leotsarev** [lanit-summer/orbit#1]
Презентация лежит здесь https://github.com/lanit-summer/orbit/blob/master/docs/%D0%A1%D0%B8%D0%BC%D1%83%D0%BB%D1%8F%D1%82%D0%BE%D1%80%20%D0%BA%D0%BE%D1%81%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%B0%D0%BF%D0%BF%D0%B0%D1%80%D0%B0%D1%82%D0%B0.ppt

Анастасия, я тебе пришлю письмо со ссылкой на сей тред, а ты зарегся на гитхабе, пришлитмне логин, я дам вам доступ, чтобй ты могла прямо здесь отвечать.
1. Ребята утверждают, что Celestia уже три года не развивается, а альтернатива (активно поддерживаемая) Stellarium http://www.stellarium.org/ru/  Вы знаете об этом? Смотрели на Stellarium? Он вас не устраивает чем-то? Или попросить ребят посмотреть? 
2. То, что есть в презентации, это все про физико-математическую модель или есть подробнее? Кому задавать вопросы про это и с кем обсуждать?
3. Есть ли конкретные пожелания про GUI? Он нужен кроссплатформенный? Пока наш план — веб.
4. Правильно ли мы понимаем, что есть часть входных данных про корабль и его параметры (мощность двигателей, как они поворачиваются и все это) и часть входных данных про конкретную программу управления кораблем? Они обе вводятся в GUI или первая часть захардкожена?
5. Конкретно ты будешь главным контактным лицом? Приглашать ли сюда Федосеева (Cc: @droggy), например?

Cc: @lanit-summer/stem

**Comment by leotsarev** [comment]
Товарищи, накидывайте еще вопросы :-)

**Comment by alobacheva** [comment]
1. Stellarium мы подробно не смотрели. если у них есть функционал аналогичный Celestia, то можно взять его. 

2. У нас нет сейчас написанной модели для полета в трехмерном пространстве, так что всё наше ТЗ к такой модели в презентации. Мы сейчас консультируемся по физике и спутникам с Александром Шаенко ( https://vk.com/shaenko ). Думаю мы сможем его привлечь и в к нашей разработке.

3. Да, в вебе удобно.

4. Они обе вводятся в GUI.

5. Контактным лицом буду я, но Федосеева тоже добавляй.

**Comment by leotsarev** [comment]
2. А зазови его сюда тоже, пожалуйста

**Comment by alobacheva** [comment]
Шаенко? Мне кажется ему будет удобнее, если вопросы как-то пачкой заслать или устроить  с ним скайп конференцию. Сюда он всё равно оперативно не будет отвечать.

**Comment by vit-vel** [comment]
А какими именно параметрами задается космический аппарат? Какова его общая модель, управляющие части, их параметры и действия, производимые с ними?

**Comment by Lexalexeev** [comment]
Если реализуем веб - хотелось бы знать, как примерно это должно выглядеть (возможно, эскиз).
Требования/пожелания по дизайну и т.п.

**Comment by dralex** [comment]
КА задается следующими параметрами:
- положение (x, y, z);
- ориентация в пространстве (вектор или набор углов ориентации);
- скорость вращения вокруг трех осей;
- размер аппарата (кубик)
- масса, в т.ч. масса топлива

Также набор управляющих параметров:
- уровень тяги
- момент вращения вокруг каждой из осей
(эти два параметра задаются через программу, т.е. таблицу - что включать и выключать в заданные моменты времени)

Для входа в атмосферу понадобятся также: предельная перегрузка и т.п.

Также нужно задавать диапазон моделирования.

Вообще предлагаю воспринять задачу творчески и добавить еще то, что нужно.

**Comment by dralex** [comment]
По интерфейсу ответ аналогичный - жестких требований нет, важно, чтобы:
а) было функционально
б) была генерация скрипта визуализации

**Comment by alobacheva** [comment]
Александр Шаенко рекомендует для создания корректной модели движения спутника гуглить "кеплеровы элементы орбиты" и "кватернионы".

**Comment by vit-vel** [comment]
Есть ли возможность посмотреть предыдущий вариант(ы) подобного проекта и узнать что в них не так?

**Comment by dralex** [comment]
Это новый проект. Не думаю, что это осмысленно, только сбиваться с курса.

**Comment by Lexalexeev** [comment]
(Дублирую из "Сделать UI для ввода параметров КА(Космического аппарата)")
Пишем сайт.
Требуется только главная страница или подразумевается меню и другие страницы?
Что планируется использовать? Хостинг? Apache?
Скорость вращения вокруг трех осей - подразумевается 3 поля для ввода? вокруг каждой оси?
Максимальные моменты вращения - вокруг каждой из осей? их тоже 3?

**Comment by dralex** [comment]
Сайт ок. Хостинг linux. Apache как фронтенд ок
Можно обойтись и одной страницей для ввода данных и второй для вывода результатов.
Если речь идет о начальной скорости, то да, вокруг каждой из трех осей. Максимальные моменты тоже вокруг каждой из трех осей (хотя можно рассмотреть простейший случай, когда стоят три одинаковых маховика).

**Comment by MarinaLysyuk** [comment]
А что в целом подразумевается под визуализацией полёта? Я сейчас пытаюсь соотнести то, что умеет Celestia, и то, что предположительно должен уметь этот наш симулятор. Может ли космический аппарат при полёте просто после каждого шага менять свои координаты (широта, долгота, расстояние от поверхности) относительно Земли, при этом будучи постоянно обращённым к ней, или он должен  именно летать в пространстве и иногда (очень часто) терять Землю и вообще какие-либо ориентиры из виду?

**Comment by dralex** [comment]
Полет может быть любым, он же управляемый. То есть аппарат может быть по-разному ориентирован, двигаться по разным орбитам, упасть на Землю и т.п. Что касается визуализации, нужно как-то универсально показать весь полет аппарата. Тут нет жестких требований, как именно располагать камеру и т.п. Главное, чтобы было красиво (тм) :) Это можно делать через скрипты на lua, но может быть есть способ лучше.

**Comment by Lexalexeev** [comment]
@dralex, можете предоставить хостинг для проверки сайта?

**Comment by dralex** [comment]
Хостинг предоставить могу на Linux. Какие технические требования?

**Comment by anna-marina** [comment]
@alobacheva как можно получить доступ к версии Орбиты, с помощью которой сейчас проводятся игры? Это необходимо для сравнения результатов тестирования

**Comment by dralex** [comment]
Сайт несколько ограничен теми параметрами, которые можно вводить при конструировании аппарата. Находится он тут: http://simulator.orbitagame.ru
Можете использовать такие логин и пароль:
LANIT
EbtuWiwyn5

**Comment by svtarasov** [comment]
Алексей добрый день!
Сейчас у нас есть С++ библиотека для расчета полета  и приложение, которое ее использует. Но нам нужно как-то проверить правильность вычислений.
Поэтому есть следующие вопросы:
1) Нет ли каких-нибудь уже расчитанных траекторий по заданным параметрам, чтобы нам можно было бы сравнить эти результаты с результатами нашей программы?
2) Есть ли какая-нибудь спецификация органичений на параметры аппарата и начальные данные с сайта? Хотелось бы иметь список этих ограничений, чтобы заимпплементить их  в нашем приложении.

**Comment by svtarasov** [comment]
closed as not actual
