### ISSUE TITLE
Формализовать структуру классов библиотеки

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#10]

**Comment by vit-vel** [comment]
Для всех имеющихся структур реализовать конструктор.
Для структуры quaternion функции, такие как normalizeQuaternion, invertQuaternion сделать в виде методов, а такие как multiQuaternions в виде перегруженных операторов. Перегрузить операторы сложения, вычитания, умножения/деления на число и другие, которые могут понадобится.
Для структуры vec все аналогично
Для структуры vec перегрузить операторы сложения, умножения,

**Comment by svtarasov** [comment]
will be implemented as part of other task
