### ISSUE TITLE
Выложить сайт на хостинг

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#14]

**Comment by svtarasov** [comment]
1) Списаться с Лешей
2) Получить логин пароль хостинга
3) Контакт @dralex или @leotsarev 
4) Выложить в github последнюю версию сайта

**Comment by svtarasov** [comment]
Оценка 8 чел*час
+ Лиза

**Comment by svtarasov** [comment]
Ребята отпишитесь по статусу задачи

**Comment by Lexalexeev** [comment]
На гитхаб выложил, разбираюсь локально с апаче, чтобы настроить все на хостинге.
Логин и пароль есть.

**Comment by svtarasov** [comment]
Выложено на бесплатный хостинг https://d3ae1959.ngrok.io/home/
