### ISSUE TITLE
Написать тесты для С++ библиотеки. Проверка вычислений

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#18]

**Comment by svtarasov** [comment]
1. Проверка вычислений по формуле
2. Разобраться с Google tests

**Comment by svtarasov** [comment]
+ Лена ( @LS-1881  )

**Comment by anna-marina** [comment]
[gtests.txt](https://github.com/lanit-summer/orbit/files/13152/gtests.txt)

**Comment by spolinaa** [comment]
Кстати говоря, самая свежая версия orbit.cpp пока лежит в ветке feature. В мастере устаревшая версия!

**Comment by svtarasov** [comment]
Полина. Лена отпишитесь по статусу задачи

**Comment by spolinaa** [comment]
У меня проблема с гугл тестами. Они не запускаются

**Comment by spolinaa** [comment]
Мы с Лизой написали парочку тестов на силу тяжести. Решили взять Catch - он легче в установке. Тесты лежат в ветке test

**Comment by svtarasov** [comment]
передвинул на спринт 2

**Comment by svtarasov** [comment]
Тесты пишем в рамках индивидуальных задач: #37 , #35 , #33 , #34 
Закрыто
