### ISSUE TITLE
Выложить инструкцию по написанию тестов с использованием Google Tests

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#19]

**Comment by svtarasov** [comment]
Оценка 2 чел*час

**Comment by svtarasov** [comment]
+ Аня

**Comment by anna-marina** [comment]
https://github.com/lanit-summer/orbit/wiki/google-tests вот здесь инструкция

**Comment by spolinaa** [comment]
Аня, напиши, пожалуйста, понятнее для неактивных пользователей VS.
