### ISSUE TITLE
Изучить вопрос биндинга Python-C

### ISSUE THREAD

**Issue by leotsarev** [lanit-summer/orbit#2]
Задача: изучить какой наиболее правильный способ сейчас делать биндинг из С в Python, сделать краткий доклад к началу работы (1 июля).
Договорились, что делают Виталик и Артем, назначить на них, когда появятся.

**Comment by svtarasov** [comment]
+ Виталик Вельямидов
+ Анна Марьина
+ Артем Крошенинников

**Comment by vit-vel** [comment]
поразбираюсь со SWIG и модулем ctypes

**Comment by svtarasov** [comment]
Артем посмотри пожалуйста на #8

**Comment by svtarasov** [comment]
Анна посмотри пожалуйста на #9

**Comment by svtarasov** [comment]
Артем,  у тебя есть логин на гитхабе? Если нет, то заведи и скажи мне - я тебя в группу добавлю

**Comment by KroArtem** [comment]
@svtarasov , есть, собственно, я в каком-то тикете уже отмечался.
#8 посмотрю, хорошо.

**Comment by KroArtem** [comment]
@svtarasov, прошу добавить в группу участников.

**Comment by vit-vel** [comment]
обзор рассмотренных способов с примерами можно посмотреть [здесь](https://github.com/lanit-summer/orbit/blob/master/docs/binding_c_in_python.txt)
