### ISSUE TITLE
Разобраться с Celestia

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#20]
1. Как загружать скрипты
2. Разобраться что есть сейчас для генерации скрипта.
3. Связаться с Артемом( @KroArtem  )  и Виталика ( @vit-vel  ) и узнать как генерится скрипт из точек траектории движения.(если генерится)

**Comment by iskrich** [comment]
Загрузка нашего скрипта происходит по уже выложенному [гайду](https://github.com/lanit-summer/orbit/blob/master/celestia/README.md) .
Генерации скрипта как таковой нету, есть только функционал питона для создания .xyzv файла.

Вкратце о том что происходит в Селестии:
- Скрипт test.cel, лишь выбирает объект нашего спутника перемещается к нему и следит за ним 
- Сам объект спутника описывается в файле [orbit.ssc](https://github.com/lanit-summer/orbit/blob/master/celestia/Orbit-test/orbit.ssc) : выбирается моделька, её параметры, начало и конец существования и самое главное её траектория. 

Формат файла orbit.xyzv : 7 значений в каждой строке:

     Время (Юлианское представление);
     Координаты x y z (в километрах);
     Скорости соответствующих координат(км/c)


Вики
[SSC] (https://en.wikibooks.org/wiki/Celestia/SSC_File)
[Траектории](https://en.wikibooks.org/wiki/Celestia/Trajectories#SampledTrajectory)
[Скрипты](https://en.wikibooks.org/wiki/Celestia/Cel_Scripting)

**Comment by svtarasov** [comment]
Считаем, что разобрались, закрываю
