### ISSUE TITLE
Разобраться с парсингом команд и параметров для корабля

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#21]
1. Проверить есть ли он в гите
2. Если нет, то попробовать написать
3. Взять вырожденный случай задачи - прямая траектория, и попробовать по заданным параметрам получить скрипт Celestia

**Comment by vit-vel** [comment]
Все сделано.
1. парсинг команд: файл [orbit_wrap.py](https://github.com/lanit-summer/orbit/blob/master/binding/orbit_wrap.py), функция `parse_input_code`
2. генерация скрипта (файла с координатами): там же, функция `generate_celestia_script`
3. вырожденный случай с прямой траекторией к Земле: файл [test,py](https://github.com/lanit-summer/orbit/blob/master/binding/test.py), функция `first_test`

**Comment by svtarasov** [comment]
Закрываю как сделанное
