### ISSUE TITLE
Посмотреть на Stellarium

### ISSUE THREAD

**Issue by leotsarev** [lanit-summer/orbit#3]
Ребята, а кто про Stellarium говорил и может посмотреть?

Cc: @lanit-summer/stem

**Comment by vit-vel** [comment]
Ничего про них не знаю, но есть еще и такие:
[KStars](https://edu.kde.org/kstars/)
[WorldWide Telescope](http://www.worldwidetelescope.org/) (увы, только для Windows)
[Space Engine](http://spaceengine.org/)

P.S. Пока что посмотреть некогда

**Comment by KroArtem** [comment]
Если вкратце: вероятнее всего, Stellarium не подходит, потому что это, по большому счету, программа-планетарий, а Селестия - программа-симулятор.
Ответ от одного из разработчиков Stellarium:
> Смотря какого космического корабля. Если речь идёт о ИСЗ, то орбиты целиком >определяются TLE и Stellarium уже очень давно умеет визуализировать положение таких >объектов. Если речь идёт об АМС или маневрирующем ИСЗ (к примеру, шаттл), то тут всё >намного сложнее и Stellarium действительно такого не умеет. Хотя должен сказать, что >ребята из Нижнего Новгорода в своём форке древней версии 0.8.2 реализовали полеты >шаттла (https://code.launchpad.net/~stellarium/stellarium/stellarium-0.8-itlab-unn). Увы, руки до >портирования этой фичи в основную ветку так и не дошли.
>Если есть желание, то можете попытаться портировать полеты АМС из Celestia в Stellarium, >хотя у них сильно разный подход - Celestia всё же симулятор, а Stellarium - планетарий.

**Comment by MarinaLysyuk** [comment]
А когда и где мы начинаем работать?

2015-06-13 22:48 GMT+03:00 Artem <notifications@github.com>:

**Comment by svtarasov** [comment]
Вопрос закрыт

**Comment by dralex** [comment]
В итоге берете скрипты celestia за основу?

**Comment by svtarasov** [comment]
Да выбрали Celestia
