### ISSUE TITLE
Сделать UI для ввода параметров КА(Космического аппарата)

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#4]
КА задается следующими параметрами:

положение (x, y, z);
ориентация в пространстве (вектор или набор углов ориентации);
скорость вращения вокруг трех осей;
размер аппарата (кубик)
масса, в т.ч. масса топлива
максимальные моменты вращения, максимальный массовый расход топлива и удельный импульс двигателя.
Также набор управляющих параметров:

уровень массового расхода топлива (больше 0 = двигатель включен)
момент вращения вокруг каждой из осей (эти два параметра задаются через программу, т.е. таблицу - что включать и выключать в заданные моменты времени)
Для входа в атмосферу понадобятся также: предельная перегрузка и т.п.

Также нужно задавать диапазон моделирования.

Вообще предлагаю воспринять задачу творчески и добавить еще то, что нужно.

**Comment by svtarasov** [comment]
Алексей Алексеев
Максим Харин
Марина Лысюк

**Comment by leotsarev** [comment]
Вроде как ребятам все равно, в каком конкретно виде будет GUI. 
Кажется разумным выбрать сайт на джанге за кроссплатформенность и простоту.

**Comment by Lexalexeev** [comment]
Пишем сайт.
Требуется только главная страница или подразумевается меню и другие страницы?
Что планируется использовать? Хостинг? Apache?
Скорость вращения вокруг трех осей - подразумевается 3 поля для ввода? вокруг каждой оси?
Максимальные моменты вращения - вокруг каждой из осей? их тоже 3?
