### ISSUE TITLE
Сделать тестовый скрипт для Celestia

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#5]

**Comment by svtarasov** [comment]
Дублирую: Шаблон скрипта: http://celestiamotherlode.net/creators/dgoyette/cel_scripting/CelScriptTemplate_v1_2.cel.txt

**Comment by KroArtem** [comment]
Необходимый минимум для того, чтобы сгенерированные данные подкинуть селестии и в каком-то виде отобразить в ней же, имеется. Однако я не собираюсь выкладывать его в репозиторий, потому что есть какой-то рукожоп, который удаляет коммиты. Сначала подожду, пока удаленные коммиты (они не отображаются в истории изменений) будут восстановлены этим самым рукожопом, а потом, спокойный за судьбу изменяемых\добавляемых файлов, сделаю коммит в репозиторий. Тикет #5 можно считать выполненным.
