### ISSUE TITLE
[BUG] Изменить цвет шрифта на сайте

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#53]
Заказчик попросил поменять свет шрифта на более для него приятный за основу можно взять сайт с симулятором орбиты

**Comment by Lexalexeev** [comment]
Взять их дизайн может быть?

**Comment by svtarasov** [comment]
Мне кажется у нас красивая картинка, можно попробовать поменять цвет шрифта на какой-нибудь с их сайта, но у них там вроде черный просто. Попробуй просто другие цвета какие-нибудь - может будет лучше. В любом случае это не первого приоритета задача. Лучше страничку с хелпом запилить
