### ISSUE TITLE
Спроектировать API для библиотеки.

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#6]
Библиотека, которая получает параметры КА и команды и выдает скрипт, описывающий орбиту.

**Comment by MarinaLysyuk** [comment]
Я сегодня немного пошерстила интернет на эту тему, из найденного и осознанного: библиотека, которую мы вроде как пишем на С, должна генерировать файл с описанием всех смен координат и прочими штуками, команды и синтаксис описаны тут: https://en.wikibooks.org/wiki/Celestia/Celx_Scripting/CELX_Lua_Methods. Вручную разработчики Celestia предлагают писать его в каком-нибудь текстовом редакторе и потом сохранять в формате .cel (или более новом .celx). Примеры готовых скриптов можно посмотреть тут: http://www.celestiamotherlode.net/catalog/scripts.php, особенно ценен Enhanced Tour of Earth, потому что, насколько я понимаю, он весьма похож на то, что от нас хотят, и сам код там написан приятно и наглядно. Для того, чтобы заставить сгенерированный скрипт заработать в Celestia, достаточно просто запустить .cel-файл с ним.
Утром более внимательно пробегусь по командам CELX и постараюсь понять, каким образом там будет происходить движение аппарата. С первого беглого просмотра из интересного я увидела перемещение его в заданную точку (координаты — широта, долгота, расстояние до Земли), ускорение времени в n раз, вывод текста в определённом месте экрана, задержка на n секунд.

**Comment by MarinaLysyuk** [comment]
Шаблон скрипта: http://celestiamotherlode.net/creators/dgoyette/cel_scripting/CelScriptTemplate_v1_2.cel.txt

**Comment by MarinaLysyuk** [comment]
Что касается координат: в Celestia их можно указать двумя способами — либо стандартные декартовы, либо сферические, в обоих случаях за точку отсчёта берётся центр выбранного объекта (в нашем случае Земли). Я попробовала оба варианта и обнаружила, что декартовы работают, мягко говоря, так себе (я запускала готовые скрипты, описывающие смену местоположения относительно Марса и Земли, потом пыталась сделать из них описание цепочки перемещений, в итоге спустя n запусков это творение сломало Целестию, и обе планеты просто перестали отображаться). Поэтому предлагаю работать со сферическими координатами, получая их из начальных пользовательских данных по стандартным формулам. С ними никаких проблем обнаружено не было.
