### ISSUE TITLE
[Design]Сформировать пакет данных для загрузки в Селестию пользователем.

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#62]

**Comment by iskrich** [comment]
> trajectory.xyzv

 - каждый раз генерится библиотекой

> script.cel

 - грубо говоря хранит информацию о том за каким кораблём следим, как следим(камера), и когда следим.

> model.3ds

- моделька будет изменяться каждый раз когда выбираем новый файл

> orbit.ssc

- создаёт класс нашего корабля, пока связывает модельку со временем старта и с траекторией.

Я ещё не уверен, но вроде как можно сделать так, что при смене корабля будет меняться только его моделька. Его поведение будет описываться файлом траектории.
`script.cel` можем менять только при смене миссии (новые даты, новая постановка камеры)
Из этих соображений пакет может включать в себя: 

`trajectory.xyzv` - в случае если заново нагенерили траекторию, но при этом миссия и корабль остались такими же.

`trajectory.xyzv`, `model.3ds` - в случае если новый корабль, новая траектория

`trajectory.xyzv`, `model.3ds`, `script.cel` - новая миссия.

**Comment by svtarasov** [comment]
Тут у меня возникают следующие вопросы:
1) Нужно где-то хранить эти файлы на сервере перед отправкой пользователю. Если у нас несколько пользователей будут одновременно пользоваться сайтом и формировать пакеты с данными - возникнет проблема имен, поэтому имена файлов должны быть уникальны
2) Если таких файлов будет много - незачем их хранить на сервере - надо как-то подчищать содержимое.
3) Нужно паковать все файлы в архив перед тем как пользователь сохранит пакет. Для этого на сайте должен быть реализован соответствующий механизм.
4) может не самая актуальная сейчас задача, но если пользователь не c Windows работает - тут надо в каком то другом виде предоставлять скрипты.

**Comment by svtarasov** [comment]
done
