### ISSUE TITLE
Исследование физики процесса

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#7]
Разобраться в формулах

**Comment by svtarasov** [comment]
Соколова Полина
Кузьмина Лиза

**Comment by leotsarev** [comment]
Привет, насколько понимаю вопрос звучит так: нужна ли посадка и взлет аппарата, или только полет по орбите?
@dralex @alobacheva можете откомментировать?

**Comment by spolinaa** [comment]
- Какие команды есть в арсенале пользователя? 
- Нужны ли команды для стабилизации КА?
- Какие двигатели должны быть у КА?

**Comment by leotsarev** [comment]
На эти вопросы вот тут даны ответы https://github.com/lanit-summer/orbit/issues/4 насколько я понимаю

**Comment by alobacheva** [comment]
Я думаю, что моделирование выхода ракеты на орбиту и вывода спутника совсем отдельная задача и ее лучше не брать, но если можно сделать стандартную заставку на эту тему, то эт было бы круто, как мне кажется.
А вот для посадки аппарата хорошо бы сделать модель.

На полет КА можно влиять двигателями и маховиками. Соответственно есть команды стабилизации, изменения положения аппарата, изменения им орбиты. 

Про двигатели имеетс ввиду модели двигателей или возможный диапазон параметров?

**Comment by spolinaa** [comment]
Пользователь сам вводит параметры двигателя, если да, то какие?

**Comment by alobacheva** [comment]
Пользователь выбирает модель двигателя, которая в свою очередь обладает рядом параметров. Для рассчета импульса нужны удельный импульс двигательной установки и максимальный массовый расход+ собственнл запас топлива.

**Comment by alobacheva** [comment]
То же самое и с маховиками, для которых актуален	максимальный управляющий момент и максимальный кинетический момент.

**Comment by dralex** [comment]
Я бы предложил упростить: игрок вводит только параметры двигателя - удельный импульс и максимальный расход топлива. Выбирать из списка готовых не надо.

**Comment by dralex** [comment]
Команды предлагаю сделать такие:

для каждого маховика (по каждой из трех осей) - включить с заданным моментом или выключить
для двигателя - включить с заданных расходом топлива и выключить
и все, больше ничего не делать

**Comment by spolinaa** [comment]
- Вращение вокруг осей производится мгновенно или с задержкой?
- При включении двигателей нужно указывать время начала/конца, время работы или выполнять, пока не встретится команда "выключить"?

**Comment by dralex** [comment]
Вращение производится как любой физический процесс, развивающийся во времени. Есть угол, угловая скорость, момент, создаваемый маховиками и т.п.

Как управлять процессом - не так важно. Можно через команды ВКЛ и ВЫКЛ и время для каждой. Можно через команду ВКЛ и продолжительность. Как эстетически будет приятнее.

**Comment by spolinaa** [comment]
Вы не могли бы привести пример работы программы при конкретных значениях?

**Comment by svtarasov** [comment]
Closed as not actual
