### ISSUE TITLE
Биндинг Python-C: Boost.Python

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#8]
Посмотреть на Boost.Python

**Comment by anna-marina** [comment]
Прочитала много статей о библиотеке boost.python, http://habrahabr.ru/post/168083/ http://habrahabr.ru/post/168233/ эти две статьи понравились больше всего. Единственный недостаток этой библиотеке - ее нужно устанавливать отдельно и она много весит. Под windows у меня не получилось с ней поработать, а вот под linux она установилась. Завтра планирую еще поработать с ней на практике.
