### ISSUE TITLE
Расчет аэродинамического нагрева: Изучение формул. Расчет коэффициента сопротивления

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#80]

**Comment by egorvarzer** [comment]
Я нашел зависимости коэф-та сопротивления Сх для пластины, цилиндра, конуса и полусферы от угла атаки. Не могу найти зависимость Сх от угла атаки для куба. Для куба нашел только два значения: куб стороной к потоку и куб ребром к потоку. Ссылка на [статью](https://github.com/lanit-summer/orbit/wiki/%D0%9A%D0%BE%D1%8D%D1%84%D1%84%D0%B8%D1%86%D0%B8%D0%B5%D0%BD%D1%82-%D0%B0%D1%8D%D1%80%D0%BE%D0%B4%D0%B8%D0%BD%D0%B0%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D1%81%D0%BE%D0%BF%D1%80%D0%BE%D1%82%D0%B8%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F) в нашей Вики.
