### ISSUE TITLE
Биндинг Python-C: distutils

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/orbit#9]
Посмотреть на distutils

**Comment by vit-vel** [comment]
Как оказалось, distutils является модулем для создания пакетов на Pyhton для их дальнейшего распространения. Он предоставляет возможность подгружать в пакет модули, написанные на С, но никак не оптимизирует создание таких модулей и требует полного соответствия Pyhton/C API, что неудобно для разработки. 
Мы же ищем средство, позволяющее создать весь связующий слой за нас.
